### PR TITLE
Fixing malformed cookies without external cookies.js lib (cookiefix)

### PR DESCRIPTION
**Pull request by teemuteemu**
New branch for fixing malformed cookies without external library.

### CODE REVIEW

**Comment by rymai** [comment]
@teemuteemu That's good but the original issue reported was happening where you try to *read* the document cookies that contains a malformed cookie.

**Comment by teemuteemu** [comment]
Okey, I see, makes it much trickier then. (Even cookies.js doesn't seem to handle that case).

**Comment by rymai** [comment]
Yes it does (I've reported the issue and the maintainer implemented a solution): ScottHamper/Cookies#48

**Comment by teemuteemu** [comment]
Then I fail to see how.

```javascript

document.cookie = 'foo="'+ JSON.stringify({"SLT":"%'lV9Z","UID":""})+'"';
Cookies.get('foo');
Uncaught URIError: URI malformed(…)
```

Using cookies-js 1.2.2

**Comment by rymai** [comment]
The thing is that trying to access a malformed cookie value will still fail, but if you try to access a key that has a valid value, this won't fail. That's the whole point... ;)

Edit:
> Edit. Ah, I checked again. Good values are returned as they should, only malformed are still throwing errors. No problem.

Exactly!

**Pull request merged**
